#!/bin/sh

# Stop immediately on error
set -e

# Switch to lambda directory
cd lambda

# Double-check linting on all files
npx eslint --fix .
# Ensure tests pass and coverage is met before push
#npx jest --colors
