name: Deploy Alexa skill

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy skill using Alexa Skill Kit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install and audit packages
        run: npm ci && npm audit --audit-level=high
        env:
          HUSKY: 0
          NODE_ENV: test
        working-directory: ./lambda/
#       - name: Install Alexa Skill Kit CLI
#         run: npm install -g ask-cli
#       - name: Execute Alexa Skill Kit deploy
#         run: ask deploy
#         env:
#           ASK_REFRESH_TOKEN: ${{ secrets.ASK_REFRESH_TOKEN }}
#           ASK_VENDOR_ID: ${{ secrets.ASK_VENDOR_ID }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SKILL_ID: ${{ secrets.SKILL_ID }}
#       - name: Set git name and email
#         run: |
#           git config --local user.email "dbowland1+bot@gmail.com"
#           git config --local user.name "github-actions[bot]"
#       - name: Commit ask-states changes
#         run: git commit -am "Update ask-states.json from deploy"
#       - name: Bump the minor version
#         run: npm version minor
#         working-directory: ./lambda/
#       - name: Push tag created by version bump
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}